---
- name: Test Users CRUD
  hosts: localhost
  vars:
    test_matrix:
      - api:
          token_action: galaxy.user.token
          base_url: http://localhost:8000
      - cli:
          token_action: galaxy.user.token
          config: /path/to/galaxy.ini
      - ui:
          base_url: http://localhost:8001/ui/
          driver: selenium-grid
  tasks:
    - include_tasks: test-users.yaml
